TRUNCATE TABLE CONJEL.QUESTOR_DIM_EMPRESA;
INSERT INTO CONJEL.QUESTOR_DIM_EMPRESA
select 
    "0" as codigoempresa, cast("1" as BYTEA) as MARCADAGUAEMPRESA, "2" as NOMEEMPRESA, cast("3" as BYTEA) as LOGOTIPOEMPRESA
from staging.empresa;