TRUNCATE TABLE CONJEL.QUESTOR_DIM_EMPRESASEGMENTO;
INSERT INTO CONJEL.QUESTOR_DIM_EMPRESASEGMENTO
select
    "0" as codigoempresa, "1" as seq, cast("2" as date) as DATAINICIOSEGMENTO, "3" as CODIGOESTAB, "4" as CODIGOSEGMENTO,
    cast("5" as date) as DATAFIMSEGMENTO, "6" as OBSERVACAOSEGMENTO, "7" as CODIGOUSUARIO, "8" as DATAHORAALTERACAO
from staging.empresasegmento;