TRUNCATE TABLE CONJEL.QUESTOR_DIM_FUNCLOCAL;
INSERT INTO CONJEL.QUESTOR_DIM_FUNCLOCAL
select 
"0" as CODIGOEMPRESA, "1" as CODIGOFUNCCONTR, "2" as DATATRANSF, "3" as CODIGOESTAB, "4" as CLASSIFORGAN,
"5" as LIVROREG, "6" as FOLHALIVROREG, "7" as FICHAREG, "8" as DATAHORACADAST, "9" as CODIGOMOTIVO,
"10" as TIPOADMRAIS, "11" as TIPOADMCAGED, "12" as TIPOAFASTSEFIP, "13" as TIPOAFASTRAIS, "14" as TIPOAFASTCAGED,
"15" as TIPOADM, "16" as TIPOTRANSF, "17" as INDICATADM, "18" as NUMEROPROCESSO, "19" as TIPOALTERACAOESOCIAL
from staging.funclocal;