TRUNCATE TABLE CONJEL.QUESTOR_DIM_TERCEIROPGTO;
INSERT INTO CONJEL.QUESTOR_DIM_TERCEIROPGTO
select
    "0" as CODIGOEMPRESA, "1" as CODIGOTERC, "2" as COMPET, "3" as SEQ, "4" as CODIGOESTAB, "5" as CLASSIFORGAN, "6" as SIGLAESTADO, 
    "7" as CODIGOMUNIC, "8" as DESCRSERVICO, "9" as DADOBANCO, "10" as MODOPGTO, "11" as TIPOCONTA, "12" as CODIGOBANCO, "13" as NUMEROAGENCIA, 
    "14" as NUMEROCONTA, "15" as DIGITOCONTA, "16" as NUMERORPA, "17" as GPSORIGEM, "18" as TIPOPAGAMENTO, cast("19" as numeric(5,2)) as PERCGPS, 
    "20" as CODIGOIMPOSTOGPS, "21" as VARIACAOIMPOSTOGPS, "22" as CODIGOOUTEMP, "23" as CODIGOCENTROCUSTO, "24" as CODIGOLOCALCTB, "25" as ORIGEMDADO,
    "26" as DIASTRABALHADOS, "27" as INDOPCCP, cast("28" as numeric(14,2)) as ACRESSAT, "29" as DATAPGTO, "30" as CODIGOIMPOSTOIRRF, "31" as VARIACAOIMPOSTOIRRF,
    "32" as GEROUTRANSACAOESOCIAL12001, "33" as NUMERODEPENDIR, "34" as DATAEMISSAO, "35" as NUMERO20, "36" as SERIE5, "37" as GEROUTRANSACAOESOCIAL12101,
    cast("38" as numeric(14,2)) as VALORORIGEMGPS, cast("39" as numeric(14,2)) as VALORDEDUZIRINSSCARNE, cast("40" as numeric(14,2)) as FAIXAIRRF
from staging.terceiropgto;