TRUNCATE TABLE CONJEL.QUESTOR_DIM_USUARIO;
INSERT INTO CONJEL.QUESTOR_DIM_USUARIO
select 
    "0" as CODIGOUSUARIO, "1" as NOMEUSUARIO, "2" as NOMEUSUARIOCOMPL, "3" as SENHAUSUARIO,
    "4" as TEMPOTOLERANCIA, "5" as HORADIARIA, cast("6" as numeric(14,2)) as CUSTOHORA, "7" as NIVELUSUARIO,
    "8" as FORMAAVISOAGENDA, "9" as DATABAIXAUSUARIO, "10" as EMAILUSUARIO, "11" as FILTROEMPRESA,
    "12" as PERFILTAREFFA, "13" as EDOCCONSULTARDOCSRECEBIDOS, "14" as EDOCINTERVCONSULTAS,
    "15" as EDOCAUTH, "16" as EDOCDATAHORAULTIMACONSULTA, "17" as DATAALTERACAO, "18" as HABILITARCHATONLINE,
    cast("19" as bytea) as FOTOUSUARIO, "20" as STATUSSINCZEN, "21" as ACEITETERMO
from staging.usuario;